version: '3'
services:
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  payment:
    image: payment
    ports:
      - 8082:8080
    environment:
      - SPRING_PROFILES_ACTIVE=container
    links:
      - zipkin

  user:
    image: user
    ports:
      - 8081:8080
    environment:
      - SPRING_PROFILES_ACTIVE=container
    links:
      - payment
      - zipkin

  movie:
    image: movie
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=container
    links:
      - user
      - zipkin