version: '3'
services:
  
  payment:
    image: payment
    ports:
      - 8082:8080
    environment:
      - SPRING_PROFILES_ACTIVE=container

  user:
    image: user
    ports:
      - 8081:8080
    environment:
      - SPRING_PROFILES_ACTIVE=container
    links:
      - payment

  movie:
    image: movie
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=container
    links:
      - user