server:
  contextPath: /movies
spring:
  profiles:
    active: dev
  application:
    name: movie
  jpa:
    show-sql: ${showSql:true}

---
spring:
  profiles: container
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1

user:
  url: http://user:8080/users/

---
spring:
  profiles: dev

server:
  port: 8080

user:
  url: http://127.0.0.1:8081/users/