spring:
  profiles:
    active: dev
  application:
    name: payment
  jpa:
    show-sql: ${showSql:true}
server:
  context-path: /payments

---
spring:
  profiles: container
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1

---
spring:
  profiles: dev
server:
  port: 8082


